"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NaveBar from "@/components/NaveBar";
import Footer from "@/components/Footer";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// Layout structure for your landing pages
export default function RootLayout({ children }) {
  const pathname = usePathname();

  // Define the paths where the Navbar and Footer SHOULD appear
  const navLinks = ["/", "/pricing", "/support", "/who-we-are", "/list-your-business"];

  // Check if the current path is in our list
  const showNavAndFooter = navLinks.includes(pathname);

  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        {/* Only show if the current path is in navLinks */}
        {showNavAndFooter && <NaveBar />}
        
        <main className="grow">
          {children}
        </main>

        {showNavAndFooter && <Footer />}
      </body>
    </html>
  );
}

