import LegalPage from "@/components/LegalPage";

export const metadata = { title: "Privacy Policy | Joe Praise" };

const sections = [
  { id: "definitions", title: "1. Definitions", paragraphs: ["This Policy uses Platform, Company, Business, Customer, User, Personal Data, Processing, Transaction Data, Verification Data, Trust Score, Business Intelligence, and Service Provider as defined terms relating to Joe Praise Smart Hub and its operations."] },
  { id: "controller", title: "2. Data Controller", paragraphs: ["Joe Praise Technologies Limited is the data controller for Personal Data processed through Joe Praise Smart Hub. Its registered office is 3rd Floor, 86-90 Paul Street, London, England, EC2A 4NE."] },
  { id: "collection", title: "3. Information We Collect", paragraphs: ["We may collect account and registration information; Business onboarding, ownership, registration, licensing, tax, address, and Verification records; Transaction and payment information; communications; Platform usage and technical information; and media or other uploaded Content.", "Payment providers process payment credentials under their own controls. We may receive Transaction status, amounts, identifiers, refunds, disputes, chargebacks, and related operational records."] },
  { id: "use", title: "4. How We Use Personal Data", paragraphs: ["Personal Data may be used to create and secure accounts, onboard and verify Businesses, operate listings and Transactions, provide support, communicate service information, prevent fraud, maintain Trust Scores, conduct analytics and business intelligence, improve features, enforce policies, and meet legal obligations."] },
  { id: "legal-basis", title: "5. Legal Basis for Processing", paragraphs: ["Processing may rely on consent, performance of a contract, compliance with legal obligations, legitimate interests, protection of vital interests, or another lawful basis available under applicable data-protection law."] },
  { id: "communications", title: "6. Marketing & Operational Communications", paragraphs: ["We may send onboarding, account, payment, security, support, policy, and Transaction communications. Marketing messages are sent where lawfully permitted, and Users may use available unsubscribe or preference controls."] },
  { id: "providers", title: "7. Service Providers & Infrastructure", paragraphs: ["Providers may include Firebase Authentication, Stripe, PayPal, DigitalOcean, MongoDB Atlas, Cloudinary, Twilio SendGrid, Brevo, Google Analytics 4, Microsoft Clarity, Meta Pixel, and other operational partners. Providers process information under their own terms and applicable contractual safeguards."] },
  { id: "analytics", title: "8. Analytics & Platform Improvement", paragraphs: ["Analytics and monitoring technologies may help us understand usage, traffic, feature interactions, conversions, advertising performance, onboarding, errors, and Platform performance. Information may be aggregated or de-identified where reasonably possible."] },
  { id: "automated-processing", title: "9. Automated Processing & Decision Support", paragraphs: ["Automation, artificial intelligence, machine learning, and business-intelligence tools may support fraud detection, moderation, Verification, Trust Score governance, recommendations, security, and operational decisions. Significant decisions remain subject to applicable legal safeguards."] },
  { id: "sharing", title: "10. Data Sharing & Disclosure", paragraphs: ["Information may be shared with authorised providers, payment and Transaction participants, professional advisers, regulators, law-enforcement bodies, courts, or parties to a corporate transaction where lawful and necessary. We do not permit providers to use Personal Data outside authorised purposes."] },
  { id: "transfers", title: "11. International Transfers", paragraphs: ["Where Personal Data is processed outside the United Kingdom, the Company uses lawful transfer mechanisms and appropriate safeguards as required by applicable law."] },
  { id: "security", title: "12. Security Measures", paragraphs: ["We use reasonable technical and organisational controls designed to protect confidentiality, integrity, availability, authentication, access, infrastructure, monitoring, backups, and incident response. No online system can be guaranteed completely secure."] },
  { id: "fraud", title: "13. Fraud Prevention & Platform Integrity", paragraphs: ["Information may be processed to detect suspicious activity, prevent fraud and abuse, protect accounts and Transactions, investigate policy violations, support disputes, and preserve marketplace integrity."] },
  { id: "retention", title: "14. Data Retention", paragraphs: ["Personal Data is retained only as long as reasonably necessary for services, contracts, legal and tax obligations, security, disputes, fraud prevention, policy enforcement, and legitimate business needs. Retention periods vary by data category and may be extended by a legal hold."] },
  { id: "rights", title: "15. User Rights", paragraphs: ["Subject to applicable law, Users may request access, rectification, erasure, restriction, portability, objection, withdrawal of consent, or review of certain automated processing and may complain to a supervisory authority. Identity verification may be required."] },
  { id: "cookies", title: "16. Cookies & Tracking Technologies", paragraphs: ["Cookies, pixels, analytics, and related technologies may support authentication, security, preferences, Platform functionality, analytics, performance, and lawful advertising. Further information appears in the Cookie Policy."] },
  { id: "links", title: "17. Third-Party Links", paragraphs: ["External services and links operate under their own policies. The Company is not responsible for independent third-party privacy or security practices."] },
  { id: "children", title: "18. Children’s Privacy", paragraphs: ["The Platform is not intended for children under 18, and we do not knowingly collect their Personal Data. Suspected child data should be reported for appropriate action."] },
  { id: "responsibilities", title: "19. Business & Customer Responsibilities", paragraphs: ["Users must provide accurate information, protect account access, respect the privacy of others, and process any Personal Data obtained through the Platform lawfully and securely."] },
  { id: "changes", title: "20. Policy Changes", paragraphs: ["This Privacy Policy may be updated periodically. Revised versions may be published with a new effective date, and additional notice may be provided where required."] },
  { id: "contact", title: "21. Contact Information", paragraphs: ["Joe Praise Smart Hub is operated by Joe Praise Technologies Limited.", "Registered Office: 3rd Floor, 86-90 Paul Street, London, England, EC2A 4NE"], contacts: [{ label: "Support", email: "support@joepraisesmarthub.co.uk" }, { label: "Onboarding", email: "onboarding@joepraisesmarthub.co.uk" }, { label: "Legal & Compliance", email: "legal@joepraisesmarthub.co.uk" }] },
];

export default function PrivacyPolicyPage() {
  return <LegalPage title="Privacy Policy" eyebrow="Effective 4th August 2026" introduction="Joe Praise Smart Hub is operated by Joe Praise Technologies Limited. This Privacy Policy explains how we collect, use, store, process, share, and protect Personal Data across the Platform, onboarding systems, communications, services, and related infrastructure." sections={sections} />;
}
