import LegalPage from "@/components/LegalPage";

export const metadata = { title: "Terms & Conditions | Joe Praise" };

const sections = [
  { id: "definitions", title: "1. Definitions", paragraphs: ["For these Terms: “Platform” means Joe Praise Smart Hub and its related website, systems, services, applications, and infrastructure; “Company”, “we”, “us”, or “our” means Joe Praise Technologies Limited; “Business” means an entity using the Platform to promote, list, market, sell, or provide products or services; “Customer” means a person or organisation using the Platform to find, purchase from, or interact with Businesses; and “User” includes Businesses and Customers.", "A “Transaction” is a customer payment successfully processed through the Platform. A “Completed Transaction” is one where payment and fulfilment are complete and no unresolved dispute or refund remains. “Subscription Plan” means a Free or future package, “Commission” means the Platform percentage fee, “Verification” means an onboarding or review process, and “Content” includes materials submitted to the Platform."] },
  { id: "platform-role", title: "2. Platform Role", paragraphs: ["Joe Praise Smart Hub is a Business Visibility, Intelligence and Growth Ecosystem that helps Businesses increase visibility, build trust, engage Customers, facilitate Transactions, and access growth services. Businesses may create profiles, display products and services, receive inquiries and payments, and participate in visibility opportunities.", "Unless expressly stated, the Platform does not manufacture, own, supply, sell, or provide listed products or services. Businesses remain responsible for their products, services, fulfilment, delivery, pricing, customer obligations, taxes, licences, permits, legal compliance, and operations.", "The Platform does not guarantee business performance, customer acquisition, sales, profitability, uninterrupted availability, or the quality of a Business’s products or services. Verification is not an endorsement, certification, warranty, or guarantee."] },
  { id: "eligibility", title: "3. Eligibility", paragraphs: ["Users must be at least 18 years old, have capacity to enter binding agreements, provide accurate and complete information, and comply with applicable laws. Businesses must operate lawfully and may be required to provide verification information during onboarding or compliance reviews.", "The Platform may refuse, suspend, or terminate access when eligibility requirements are not satisfied."] },
  { id: "accounts", title: "4. Account Registration & Security", paragraphs: ["Users may need an account for certain features and agree to provide current information, protect login credentials, correct inaccurate information, and accept responsibility for account activity. Third-party services, including Firebase Authentication, may support access and security.", "Users must not impersonate others, create fraudulent accounts, share credentials without authorisation, or attempt unauthorised access. Accounts may be restricted or terminated for fraud, abuse, security risks, policy violations, or unlawful activity."] },
  { id: "services", title: "5. Platform Services", paragraphs: ["Services may include onboarding, listings, customer engagement tools, Transactions, Subscription Plans, visibility opportunities, analytics, reporting, communications, reviews, and marketplace infrastructure. Availability may depend on the selected Subscription Plan.", "Analytics, performance reports, growth insights, business analysis, advisory support, artificial intelligence, machine learning, automation, and predictive outputs are informational tools—not financial, legal, tax, investment, accounting, or professional advice. Businesses remain responsible for evaluating outputs and making their own decisions.", "The Platform may modify, improve, restrict, suspend, or discontinue features, plans, or services for operational, legal, security, or business reasons. New tools and integrations may be introduced without amending these Terms when consistent with Platform operations."] },
  { id: "communications", title: "6. Communications", paragraphs: ["Users consent to operational and service communications including onboarding notices, account and payment notifications, security alerts, support messages, policy updates, and transactional emails. Communications may use providers including Twilio SendGrid. Users must maintain valid contact information."], contacts: [{ label: "Support", email: "support@joepraisetechnologies.co.uk" }, { label: "Onboarding", email: "onboarding@joepraisetechnologies.co.uk" }, { label: "Legal & Compliance", email: "legal@joepraisetechnologies.co.uk" }] },
  { id: "subscriptions", title: "7. Subscription Plans", paragraphs: ["The Platform may offer Free or other Subscription Plans with different features, limits, pricing, and benefits, including listing, upload, category, Transaction, verification, analytics, visibility, and support provisions. Paid subscriptions are billed yearly unless otherwise stated.", "The Platform may change pricing or features, introduce or discontinue plans, and apply reasonable limits for sustainability, security, abuse prevention, or fair use. Where practical, reasonable notice may be provided before material changes."] },
  { id: "payments", title: "8. Payments & Transactions", paragraphs: ["Payments between Customers and Businesses may be facilitated through third-party providers, including Stripe. A Completed Transaction requires successful payment, completed fulfilment, and no active unresolved refund, dispute, or chargeback.", "Transaction activity may be monitored for fraud prevention, dispute management, security, analytics, compliance, and marketplace integrity. Transactions may be delayed, reviewed, restricted, or suspended where fraud, abuse, suspicious activity, chargeback risk, policy breaches, or legal concerns arise."] },
  { id: "commission", title: "9. Commission & Processing Fees", paragraphs: ["Current Platform commissions are 10% for Physical Products, 15% for Services, and 20% for Digital Products. Rates may vary by listing type, Subscription Plan, promotion, or commercial arrangement and may be updated as published in the Payments & Commission Policy.", "Third-party processing fees, including Stripe fees, are separate and are the Business’s responsibility. Commissions, processing costs, dispute deductions, chargebacks, refunds, or authorised adjustments may be deducted before payouts. Businesses remain responsible for taxes, VAT, accounting, and regulatory compliance."] },
  { id: "payouts", title: "10. Payouts, Reserves & Withdrawals", paragraphs: ["Eligible payouts may be released on a schedule, including weekly cycles where applicable. The Platform may use withdrawal thresholds, reserve holds, rolling reserves, verification holds, or review periods for fraud prevention, disputes, security, compliance, or marketplace protection.", "Payouts may be delayed, suspended, or withheld for unresolved disputes, fraud risks, incomplete verification, chargebacks, or suspected policy violations. External payment and banking systems may also affect payout timing."] },
  { id: "verification", title: "11. Verification", paragraphs: ["Business onboarding and verification may review registration, identity, contact details, operational legitimacy, or supporting documentation. Requirements and levels may vary by plan, documentation, activity, or compliance review.", "Verification is not endorsement, certification, legal or regulatory approval, warranty, or guarantee. The Platform may refuse or revoke verification, downgrade status, request more documents, or suspend listings for inaccurate information, suspicious activity, fraud concerns, or policy breaches."] },
  { id: "trust-score", title: "12. Trust Score", paragraphs: ["A Trust Score or similar indicator may consider verification, reviews, Transaction history, complaints, profile completeness, Platform activity, and other operational signals. It is informational only and is not certification, endorsement, legal approval, financial assessment, or a guarantee of quality, reliability, safety, or future performance.", "The Platform may review, update, suspend, or modify its Trust Score methodology at any time."] },
  { id: "business-responsibilities", title: "13. Business Responsibilities", paragraphs: ["Businesses must provide accurate information, operate lawfully, honour customer commitments, fulfil responsibly, maintain accurate pricing and listings, comply with laws, and communicate professionally. They remain responsible for quality, delivery, warranties, taxes, licences, permits, and legal compliance.", "Businesses must not commit fraud, misrepresent offerings, manipulate reviews, upload unlawful or misleading Content, process prohibited Transactions, or use the Platform illegally or deceptively. Violations may lead to listing removal, reduced visibility, suspension, payout holds, verification revocation, or termination."] },
  { id: "customer-responsibilities", title: "14. Customer Responsibilities", paragraphs: ["Customers agree to provide accurate information, use lawful payment methods, engage respectfully, and use the Platform responsibly. They must not submit fraudulent payments, abuse disputes, manipulate reviews, impersonate others, or engage in unlawful or harmful conduct.", "Customer access may be suspended or restricted for misuse, fraud, abuse, or policy violations."] },
  { id: "prohibited-activities", title: "15. Prohibited Activities", paragraphs: ["Users must not engage in unlawful activity, distribute fraudulent or misleading information, process unauthorised Transactions, infringe intellectual property, upload malicious code, interfere with operations or security, manipulate reviews or analytics, impersonate others, harass Users, or otherwise misuse the Platform.", "Businesses must not list illegal products or services, counterfeit goods, fraudulent schemes, misleading offers, unauthorised financial activities, unlawful digital services, or prohibited offerings. Suspected violations may result in investigation, Content removal, suspension, payout restrictions, verification revocation, Transaction cancellation, or permanent termination."] },
  { id: "content", title: "16. Content & Intellectual Property", paragraphs: ["Users retain ownership of submitted Content but grant the Platform a non-exclusive, worldwide, royalty-free licence to host, display, reproduce, distribute, promote, optimise, and use it for Platform operations, promotion, development, analytics, and improvement.", "Users must hold all necessary rights and may not upload infringing, unlawful, misleading, or non-compliant Content. The Platform may remove or restrict Content presenting legal, policy, infringement, or operational concerns.", "Joe Praise Smart Hub and Joe Praise Technologies Limited branding, systems, software, trademarks, logos, infrastructure, and proprietary materials remain Company intellectual property unless stated otherwise."] },
  { id: "availability", title: "17. Platform Availability", paragraphs: ["The Platform may rely on DigitalOcean, MongoDB Atlas, Firebase Authentication, Stripe, PayPal, Cloudinary, Twilio SendGrid, Brevo, and other providers. It does not guarantee uninterrupted availability, error-free functionality, or continuous operation.", "Maintenance, updates, security actions, technical failures, third-party outages, or improvements may cause interruptions. Systems may be modified, maintained, restricted, or discontinued where reasonably necessary."] },
  { id: "liability", title: "18. Limitation of Liability", paragraphs: ["To the fullest extent permitted by law, the Company and related parties are not liable for indirect loss, lost profit or opportunity, reputational damage, lost data, interruptions, customer disputes, delivery failures, business losses, or consequential damages arising from Platform use.", "The Platform does not guarantee business success, Customers, Transactions, revenue, performance, or uninterrupted access and is not responsible for Business offerings, Customer conduct, fulfilment, pricing or delivery disputes, or agreements between Businesses and Customers. Liability that cannot legally be excluded remains unaffected."] },
  { id: "force-majeure", title: "19. Force Majeure", paragraphs: ["The Platform is not liable for delay, interruption, failure, or inability to perform caused by events beyond reasonable control, including natural disasters, war, terrorism, unrest, cyber-attacks, internet or power failures, government action, pandemics, strikes, or third-party provider failures."] },
  { id: "indemnity", title: "20. Indemnity", paragraphs: ["Businesses and Users agree to indemnify Joe Praise Technologies Limited and its officers, directors, employees, contractors, affiliates, and partners against claims, liabilities, loss, damage, costs, or expenses arising from Terms violations, unlawful conduct, Platform misuse, intellectual-property infringement, business operations, customer disputes, regulatory breaches, or negligent acts or omissions."] },
  { id: "termination", title: "21. Suspension & Termination", paragraphs: ["The Platform may suspend or terminate accounts, restrict features, remove listings, withhold payouts, revoke verification, or limit access for fraud, suspicious activity, repeated disputes, unlawful or abusive conduct, misleading listings, non-payment, security concerns, operational risks, or violations.", "Users may stop using the Platform subject to outstanding obligations, disputes, payments, or compliance reviews. Suspension or termination does not remove liabilities accrued beforehand."] },
  { id: "related-policies", title: "22. Privacy & Related Policies", paragraphs: ["Use is also governed by the Privacy Policy, Payments & Commission Policy, Refunds & Disputes Policy, Business Listing Policy, Reviews Policy, Cookie Policy, and additional operational policies introduced by the Platform. Those policies form part of these Terms."] },
  { id: "disputes", title: "23. Dispute Resolution", paragraphs: ["Before formal proceedings, Users are encouraged to contact the Platform for informal resolution. The Platform will make reasonable efforts to investigate complaints and facilitate resolution where appropriate. This does not limit legal rights available under applicable law."] },
  { id: "governing-law", title: "24. Governing Law & Jurisdiction", paragraphs: ["These Terms are governed by the laws of England and Wales. Disputes relating to the Platform, these Terms, or related policies are subject to the exclusive jurisdiction of the courts of England and Wales."] },
  { id: "changes", title: "25. Changes & Electronic Acceptance", paragraphs: ["The Platform may update, modify, or revise these Terms periodically. Updated versions may be published with revised effective dates. Continued use following updates constitutes acceptance of the revised Terms.", "Selecting the Platform Agreements checkbox and submitting a Business application constitutes the User’s electronic acceptance of these Terms and the policies identified in that declaration. The electronic acceptance has the same effect as agreeing to the Terms in writing, subject to applicable law."] },
  { id: "contact", title: "26. Contact Information", paragraphs: ["Joe Praise Smart Hub is operated by Joe Praise Technologies Limited.", "Registered Office: 3rd Floor, 86-90 Paul Street, London, England, EC2A 4NE"], contacts: [{ label: "Support", email: "support@joepraisetechnologies.co.uk" }, { label: "Onboarding", email: "onboarding@joepraisetechnologies.co.uk" }, { label: "Legal & Compliance", email: "legal@joepraisetechnologies.co.uk" }] },
];

export default function TermsOfUsePage() {
  return <LegalPage title="Terms & Conditions" eyebrow="Effective 4th August 2026" introduction="These Terms & Conditions govern the use of Joe Praise Smart Hub, operated by Joe Praise Technologies Limited. By accessing or using the Platform, you agree to comply with and be bound by these Terms. If you do not agree, you must not access or use the Platform." sections={sections} />;
}
